{% set name = "IngeoML" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/IngeoML-{{ version }}.tar.gz
  sha256: 94b422a667b5a294cecea9d1d178956aef920ce17bff82e1cf9a8604a9bd10e7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - scikit-learn >=1.3.0
    - python >=3.7
    - jax
    - optax

test:
  imports:
    - IngeoML
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/IngeoML
  summary: Machine Learning Tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
