{% set name = "IngeoML" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/IngeoML-{{ version }}.tar.gz
  sha256: 65aa0e64535cae08a99d6061a0a5327979996858f2d26a8ace2722dbaa98c6a1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - scikit-learn >=1.3.0
    - python >=3.7
    - jax
    - optax

test:
  imports:
    - IngeoML
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/IngeoML
  summary: Machine Learning Tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
