{% set name = "IngeoML" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/IngeoML-{{ version }}.tar.gz
  sha256: 16d866a171249fab74d1a8a15f4ce6d0b415c20c5c170bd435841064dc9ac355

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - scikit-learn >=1.3.0
    - python >=3.7

test:
  imports:
    - IngeoML
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/IngeoML
  summary: Machine Learning Tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
