{% set name = "IngeoML" %}
{% set version = "0.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/IngeoML-{{ version }}.tar.gz
  sha256: 2f00bb3a2802d1919c4e08e24c7bf5bb22b45ad2b1e90f2d26f508c315e9562b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - scikit-learn >=1.3.0
    - python >=3.7
    - jax
    - optax

test:
  imports:
    - IngeoML
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/IngeoML
  summary: Machine Learning Tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
